### ISSUE TITLE
Dataframe pre-work

### ISSUE THREAD

**Issue by dantstephens** [deuce-shaw/Project3#5]
### User story
As an engineering team, we need a common file with the source data imported into a dataframe so that we can complete data transformation work. 

### Acceptance criteria:

- Only columns in the designed database are imported into the CSV
- Rows that contain a negative value in the 'age_start_years' column are dropped
- Rows that do not contain any for conditions are dropped

**Comment by MaggiePuch** [comment]
The CSV column specific code has been added to the Project3Primary account on the main branch. 

Code for rows not containing a condition to be dropped - written and need to check/confirm before deploying to the main branch.

**Comment by MaggiePuch** [comment]
Confirmed conditional parameter is working properly. Going to push it to the main branch in the Project3Primary as everyone will need it for their portions. 
Also pushing updated CSV that I updated in excel due to 'NA' value causing me so much trouble. I did an excel update (find/replace all 'NA' with blank).
